sonar.projectKey=nestjs-template
sonar.sources=src
sonar.tests=test

# global exclusions (optional extra safety)
sonar.exclusions=**/migrations/**
sonar.test.exclusions=**/migrations/**

# TS-specific exclusions (belt & suspenders)
sonar.typescript.exclusions=**/migrations/**

sonar.issue.ignore.multicriteria=bootstrapMain
sonar.issue.ignore.multicriteria.bootstrapMain.ruleKey=typescript:S7785
sonar.issue.ignore.multicriteria.bootstrapMain.resourceKey=src/main.ts